#+LaTeX_CLASS: phd
#+OPTIONS: author:nil date:nil title:nil toc:nil

#+LaTeX_HEADER: \usepackage{booktabs}
#+LaTeX_HEADER: \graphicspath{{expt/}}

# ---------------------------

#+LaTeX_HEADER: \newcommand{\Rey}{\ensuremath{\mathrm{Re}}}
#+LaTeX_HEADER: \newcommand{\avg}[1]{\ensuremath{\overline{#1}}}
#+LaTeX_HEADER: \newcommand{\tenpow}[1]{\ensuremath{\times 10^{#1}}}
#+LaTeX_HEADER: \newcommand{\pder}[2]{\ensuremath{\frac{\partial#1}{\partial#2}}}
#+LaTeX_HEADER: \newcommand{\Eqref}[1]{Equation~\eqref{#1}}
#+LaTeX_HEADER: \newcommand{\Tabref}[1]{Table~\ref{#1}}
#+LaTeX_HEADER: \newcommand{\Figref}[1]{Figure~\ref{#1}}
#+LaTeX_HEADER: \newcommand{\Appref}[1]{Appendix~\ref{#1}}

#+BEGIN_EXPORT latex
%%********************************Frontmatter***********************
% In frontmatter everything comes with roman numbering
\pagenumbering{roman}
\setcounter{page}{1}

%*******************************************************************
%                         Title Page
%*******************************************************************
\title{Essential \LaTeX\ Templates for Report Writing}
\author{My name}

%% Print the date. Today's date comes by default, change it here to
%% other date format, if required:

%\date{\today}
%\date{10 Mar 2016}


%% The type of the report can be set here

\reporttype{A Seminar Report}
%\reporttype{A Thesis}
%\reporttype{A Dissertation}
%\reporttype{A Project Report}

%% Name of the degree
\degree{Doctor of Philosophy}
%\degree{Master of Technology}


%% Department/Centre Name
\dept{Department of Chemical Engineering}

%% Supervisor and cosupervisor/excosupervisor are not essential parts
%% of a report title page, as it is your report!

%% But if you **have** to put it uncomment these
%\supervisor{Supervisor name}
%\cosupervisor{Co-super name}
%\excosupervisor{External Supervisor}

%% Roll number
\rollnum{Roll No. ....}

\maketitle

%*******************************************************************
%                         Copyright Page
%*******************************************************************
%\mycopyright

%*******************************************************************
%                         Dedication Page
%*******************************************************************
\dedication[Dedicated to \ldots]
%\addintoc{Dedication}

%*******************************************************************
%                        Certificate Page
%*******************************************************************
%\makecertificate[change title name]{report type}
\makecertificate{seminar report}
%\makecertificate{thesis}
%\makecertificate{dissertation}
%\makecertificate{project report}

%\addintoc{Certificate}

%*******************************************************************
%                         Approval Sheet
%*******************************************************************
%\makeapproval{thesis}
%\makeapproval{dissertation}

%*******************************************************************
%                          Declaration
%*******************************************************************
%==================================dec.tex================================
%
\begin{Declaration}
\noindent
I declare that this written submission represents my ideas in my own words and where others' ideas or words have been included, I have adequately cited and referenced the original sources. I declare that I have properly and accurately acknowledged all sources used in the production of this report. I also declare that I have adhered to all principles of academic honesty and integrity and have not misrepresented or fabricated or falsified any idea/data/fact/source in my submission. I understand that any violation of the above will be a cause for disciplinary action by the Institute and can also evoke penal action from the sources which have thus not been properly cited or from whom proper permission has not been taken when needed.

%
%
%
%
%
%
%

\DecSign[\today]



%
\end{Declaration}
%========================================================================
% \include{dec}
%\addintoc{Declaration}

%******************************************************************
%                          Abstract
%******************************************************************
%============================= abs.tex================================
\begin{Abstract}
This document contains essential templates required to write technical
reports using \LaTeX.  Particularly it shows how to create an
equation, figure, table, symbols list, and bibliographic citation in a \LaTeX\
document.
%
%
%
%
%
\end{Abstract}
%=======================================================================
% \include{abs}

%******************************************************************
%                         Contents list
%******************************************************************
%\figurespagefalse
%\tablespagefalse
\makecontents % Creats toc, lof, and lot

%******************************************************************
%                        Notations
%******************************************************************
\notations[4cm]{List of Symbols}

%%********************************Mainmatter***********************
% In mainmatter everything comes with arabic numbering
\cleardoublepage
\setcounter{page}{1}
\pagenumbering{arabic}
#+END_EXPORT

* Literature Survey
  Cite this file cite:Smith99,



#+BEGIN_EXPORT latex
%****************************************************************
%                         Appendices
%****************************************************************
%% Additional, supporting material, such as codes, derivations, etc., can be placed in the appendix
\appendix
\chapter{Supporting Material}
#+END_EXPORT

bibliographystyle:iitbauthyr
bibliography:./mylit.bib

#+BEGIN_EXPORT latex
%*******************************************************************
%                         List of publications
%******************************************************************
%%%
\listofpublications


\noindent Put your publications from the thesis here. The packages \texttt{multibib} or \texttt{bibtopic} or \texttt{biblatex} or enumerate environment or thebibliography environment etc. can be used to handle multiple different bibliographies in the document.
% \include{pub}

%*******************************************************************
%                        Acknowledgements
%*******************************************************************
%%%
\acknowledgments

This section is for the acknowledgments. Please keep this brief and resist the temptation of writing flowery prose! Do include all those who helped you, e.g. other faculty/staff you consulted, colleagues who assisted etc.






\signature{\today}
% \include{ack}

%*******************************************************************
%                        About author
%*******************************************************************
% \colophon % remove this command while using this file.

% GAME OVER
%*******************************************************************
\end{document}
#+END_EXPORT
